/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004;

import ca.ulaval.glo2004.domain.CountryDTO;
import ca.ulaval.glo2004.domain.HealthMesureDTO;
import ca.ulaval.glo2004.domain.Link.LinkType;
import ca.ulaval.glo2004.domain.LinkDTO;
import ca.ulaval.glo2004.domain.Utility;
import ca.ulaval.glo2004.domain.WorldController;
import ca.ulaval.glo2004.domain.WorldObserver;
import ca.ulaval.glo2004.ui.DrawingPanel;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author charl
 */
public class main_window_Simulation extends javax.swing.JFrame implements WorldObserver {

    public DrawingPanel drawingPanel;
    public WorldController worldController = new WorldController();
    
    public List<Point> countryPts = new ArrayList<>();
    public CountryDTO countrySelected = null;

    public enum Mode {Idle, Create, Select};
    public Mode mode = Mode.Idle;
    private int test = 0;
    private CountryDTO onHoverCountry = null; //Je sais que c'est pas bien, mais pour test, on va faire ca.
    private Point onHoverMousePosition = new Point(); //Je sais que c'est pas bien, mais pour test, on va faire ca.
    private JFileChooser openFileChooser; 
    private JFileChooser saveFileChooser;
    
    /**
     * Creates new form main_window_test
     */
    public main_window_Simulation() {
        initComponents();

        drawingPanel = new DrawingPanel(this, jPanelConceptionDraw);
        jPanelConceptionDraw.add(drawingPanel);
        openFileChooser = new JFileChooser();
        saveFileChooser = new JFileChooser();
        
        worldController.Subscribe(this);
    }
    
    @Override
    public void OnSimulationTick(int day, int deads, int infected) {
        System.err.println("Nouveau jour!");
        jLabelDayElapsed.setText(String.valueOf(day));
        jLabelDead.setText(String.valueOf(deads));
        jLabelCase.setText(String.valueOf(infected));
        
        drawingPanel.repaint();
    }
    
    @Override
    public void OnLinksUpdated() {
        UpdateJLinkList();
    }
    
    private void UpdateJLinkList() {
        DefaultListModel listModel = new DefaultListModel();
        for(LinkDTO l: worldController.GetLinks()){
            listModel.addElement(l.Id);
        }
        jlistLinks.setModel(listModel);
        drawingPanel.repaint();
    }
    
    private void SelectCountry(Point mousePosition) {
        CountryDTO selected = Utility.SelectCountry(worldController.GetCountries(), mousePosition);
        SetSelectedCountry(selected);
    }
    
    private void SetSelectedCountry(CountryDTO country) {
        if(countrySelected != null) {
            worldController.UpdateSelectionStateCountry(countrySelected.Id, false);
        }
        
        if(country != null) {
            countrySelected = country;
            worldController.UpdateSelectionStateCountry(countrySelected.Id, true);
            drawingPanel.repaint();
        } else {
            countrySelected = null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton10 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanelContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanelUndoRedoButtons = new javax.swing.JPanel();
        jBtnUndo = new javax.swing.JButton();
        jBtnRedo = new javax.swing.JButton();
        jPanelMainButtons = new javax.swing.JPanel();
        jBtnReset = new javax.swing.JButton();
        jBtnPause = new javax.swing.JButton();
        jBtnPlay = new javax.swing.JButton();
        jLayeredPane = new javax.swing.JLayeredPane();
        jPanelConception = new javax.swing.JPanel();
        jPanelConceptionDraw = new javax.swing.JPanel();
        jPanelConceptionTool = new javax.swing.JPanel();
        jPanelConceptionTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelConceptionContainer = new javax.swing.JPanel();
        jPanelCountry = new javax.swing.JPanel();
        jToggleButtonCreateCountry = new javax.swing.JToggleButton();
        jButtonRemoveCountry = new javax.swing.JButton();
        jButtonEditCountry = new javax.swing.JButton();
        jPanelCountryInfo = new javax.swing.JPanel();
        LabelCountryName = new javax.swing.JLabel();
        jLabelCountryPop = new javax.swing.JLabel();
        jTextCountryName = new javax.swing.JTextField();
        jTextCountryPop = new javax.swing.JTextField();
        jPanelRegion = new javax.swing.JPanel();
        jButtonAddRegion = new javax.swing.JButton();
        jButtonRemoveRegion = new javax.swing.JButton();
        jButtonEditRegion = new javax.swing.JButton();
        jPanelLink = new javax.swing.JPanel();
        jButtonAddLink = new javax.swing.JButton();
        jButtonRemoveLink = new javax.swing.JButton();
        jComboBoxLinkType = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlistLinks = new javax.swing.JList<>();
        jButtonSwitchSimulation = new javax.swing.JButton();
        jPanelSimulation = new javax.swing.JPanel();
        jPanelSimulationDraw = new javax.swing.JPanel();
        jPanelSimulationTool = new javax.swing.JPanel();
        jPanelSimulationTitle = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanelSimulationContainer = new javax.swing.JPanel();
        jPanelDeseaseParams = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelMortalityRate = new javax.swing.JPanel();
        jLabelTitleMortalityRate = new javax.swing.JLabel();
        jTextFieldMortalityRate = new javax.swing.JTextField();
        jPanelReproductionRate = new javax.swing.JPanel();
        jLabelTitleReproductionRate = new javax.swing.JLabel();
        jTextFieldReproductionRate = new javax.swing.JTextField();
        jPanelCuredRate = new javax.swing.JPanel();
        jLabelTitleCuredRate = new javax.swing.JLabel();
        jTextFieldCuredRate = new javax.swing.JTextField();
        jPanelTransmissionRate = new javax.swing.JPanel();
        jLabelTitleTransmissionRate = new javax.swing.JLabel();
        jTextFieldTransmissionRate = new javax.swing.JTextField();
        jButtonApplyDisease = new javax.swing.JButton();
        jPanelMesureParams = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanelAdhesionRate1 = new javax.swing.JPanel();
        jLabelTitleMesureName = new javax.swing.JLabel();
        jTextFieldMesureName = new javax.swing.JTextField();
        jPanelAdhesionRate = new javax.swing.JPanel();
        jLabelTitleAdhesionRate = new javax.swing.JLabel();
        jTextFieldAdhesionRate = new javax.swing.JTextField();
        jPanelReproductionRate1 = new javax.swing.JPanel();
        jLabelActive = new javax.swing.JLabel();
        jCheckBoxActive = new javax.swing.JCheckBox();
        jButtonApplyMesure = new javax.swing.JButton();
        jButtonSwitchConception = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanelOverview = new javax.swing.JPanel();
        jPanelCase = new javax.swing.JPanel();
        jLabelTitleCase = new javax.swing.JLabel();
        jLabelCase = new javax.swing.JLabel();
        jPanelDead = new javax.swing.JPanel();
        jLabelTitleDead = new javax.swing.JLabel();
        jLabelDead = new javax.swing.JLabel();
        jPanelDayElapsed = new javax.swing.JPanel();
        jLabelTitleDayElapsed = new javax.swing.JLabel();
        jLabelDayElapsed = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        NouveauMenu = new javax.swing.JMenuItem();
        ChargerMenu = new javax.swing.JMenuItem();
        SauvegarderMenu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jFormattedTextField1.setText("jFormattedTextField1");

        jButton10.setText("jButton10");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jButton10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel3)))
                .addContainerGap(430, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(96, 96, 96))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simudémie");

        jPanelContainer.setLayout(new javax.swing.BoxLayout(jPanelContainer, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelUndoRedoButtons.setLayout(new java.awt.GridBagLayout());

        jBtnUndo.setText("Undo");
        jBtnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUndoActionPerformed(evt);
            }
        });
        jPanelUndoRedoButtons.add(jBtnUndo, new java.awt.GridBagConstraints());

        jBtnRedo.setText("Redo");
        jBtnRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRedoActionPerformed(evt);
            }
        });
        jPanelUndoRedoButtons.add(jBtnRedo, new java.awt.GridBagConstraints());

        jPanelMainButtons.setMinimumSize(new java.awt.Dimension(200, 25));
        jPanelMainButtons.setLayout(new java.awt.GridBagLayout());

        jBtnReset.setText("Reset");
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });
        jPanelMainButtons.add(jBtnReset, new java.awt.GridBagConstraints());

        jBtnPause.setText("Pause");
        jBtnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPauseActionPerformed(evt);
            }
        });
        jPanelMainButtons.add(jBtnPause, new java.awt.GridBagConstraints());

        jBtnPlay.setText("Play");
        jBtnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPlayActionPerformed(evt);
            }
        });
        jPanelMainButtons.add(jBtnPlay, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jPanelUndoRedoButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jPanelMainButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 604, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelUndoRedoButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMainButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelContainer.add(jPanel1);

        jLayeredPane.setLayout(new java.awt.CardLayout());

        jPanelConceptionDraw.setBackground(new java.awt.Color(255, 255, 255));
        jPanelConceptionDraw.setMinimumSize(new java.awt.Dimension(100, 10));
        jPanelConceptionDraw.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelConceptionDrawMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelConceptionDrawMouseMoved(evt);
            }
        });
        jPanelConceptionDraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelConceptionDrawMousePressed(evt);
            }
        });

        jPanelConceptionTool.setMaximumSize(new java.awt.Dimension(500, 2147483647));
        jPanelConceptionTool.setMinimumSize(new java.awt.Dimension(200, 465));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Conception");

        javax.swing.GroupLayout jPanelConceptionTitleLayout = new javax.swing.GroupLayout(jPanelConceptionTitle);
        jPanelConceptionTitle.setLayout(jPanelConceptionTitleLayout);
        jPanelConceptionTitleLayout.setHorizontalGroup(
            jPanelConceptionTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConceptionTitleLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1)
                .addContainerGap(124, Short.MAX_VALUE))
            .addComponent(jSeparator2)
        );
        jPanelConceptionTitleLayout.setVerticalGroup(
            jPanelConceptionTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConceptionTitleLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelCountry.setBackground(new java.awt.Color(230, 230, 230));
        jPanelCountry.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButtonCreateCountry.setText("Créer pays");
        jToggleButtonCreateCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCreateCountryActionPerformed(evt);
            }
        });
        jPanelCountry.add(jToggleButtonCreateCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, -1));

        jButtonRemoveCountry.setText("Supprimer le pays");
        jButtonRemoveCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveCountryActionPerformed(evt);
            }
        });
        jPanelCountry.add(jButtonRemoveCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 320, -1));

        jButtonEditCountry.setText("Editer le pays");
        jPanelCountry.add(jButtonEditCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 320, -1));

        LabelCountryName.setText("Nom du pays");

        jLabelCountryPop.setText("Population");

        jTextCountryName.setText("Nom");
        jTextCountryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCountryNameActionPerformed(evt);
            }
        });

        jTextCountryPop.setText("10");

        javax.swing.GroupLayout jPanelCountryInfoLayout = new javax.swing.GroupLayout(jPanelCountryInfo);
        jPanelCountryInfo.setLayout(jPanelCountryInfoLayout);
        jPanelCountryInfoLayout.setHorizontalGroup(
            jPanelCountryInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCountryInfoLayout.createSequentialGroup()
                .addGroup(jPanelCountryInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCountryPop)
                    .addComponent(LabelCountryName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanelCountryInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextCountryName, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(jTextCountryPop))
                .addContainerGap())
        );
        jPanelCountryInfoLayout.setVerticalGroup(
            jPanelCountryInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCountryInfoLayout.createSequentialGroup()
                .addGroup(jPanelCountryInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCountryName)
                    .addComponent(jTextCountryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCountryInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCountryPop)
                    .addComponent(jTextCountryPop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanelCountryInfo.setVisible(false);

        jPanelCountry.add(jPanelCountryInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 340, 70));

        jPanelConceptionContainer.add(jPanelCountry);

        jPanelRegion.setBackground(new java.awt.Color(230, 230, 230));
        jPanelRegion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAddRegion.setText("Ajouter region");
        jPanelRegion.add(jButtonAddRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, -1));

        jButtonRemoveRegion.setText("Supprimer la region");
        jPanelRegion.add(jButtonRemoveRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 320, -1));

        jButtonEditRegion.setText("Editer la region");
        jPanelRegion.add(jButtonEditRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 320, -1));

        jPanelConceptionContainer.add(jPanelRegion);

        jPanelLink.setBackground(new java.awt.Color(230, 230, 230));
        jPanelLink.setPreferredSize(new java.awt.Dimension(330, 150));
        jPanelLink.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAddLink.setText("Ajouter un lien");
        jButtonAddLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddLinkActionPerformed(evt);
            }
        });
        jPanelLink.add(jButtonAddLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, -1));

        jButtonRemoveLink.setText("Supprimer un lien");
        jButtonRemoveLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveLinkActionPerformed(evt);
            }
        });
        jPanelLink.add(jButtonRemoveLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 320, -1));

        jComboBoxLinkType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terrestre", "Maritime", "Aerien" }));
        jPanelLink.add(jComboBoxLinkType, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 140, -1));
        jPanelLink.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 330, 10));

        jlistLinks.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlistLinksValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jlistLinks);

        jPanelLink.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 310, 60));

        jPanelConceptionContainer.add(jPanelLink);

        jButtonSwitchSimulation.setText("Passer en simulation");
        jButtonSwitchSimulation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSwitchSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSwitchSimulationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConceptionToolLayout = new javax.swing.GroupLayout(jPanelConceptionTool);
        jPanelConceptionTool.setLayout(jPanelConceptionToolLayout);
        jPanelConceptionToolLayout.setHorizontalGroup(
            jPanelConceptionToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConceptionToolLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanelConceptionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanelConceptionContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConceptionToolLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSwitchSimulation, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelConceptionToolLayout.setVerticalGroup(
            jPanelConceptionToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConceptionToolLayout.createSequentialGroup()
                .addComponent(jPanelConceptionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanelConceptionContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSwitchSimulation)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelConceptionLayout = new javax.swing.GroupLayout(jPanelConception);
        jPanelConception.setLayout(jPanelConceptionLayout);
        jPanelConceptionLayout.setHorizontalGroup(
            jPanelConceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConceptionLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanelConceptionDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addComponent(jPanelConceptionTool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelConceptionLayout.setVerticalGroup(
            jPanelConceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConceptionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelConceptionDraw, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelConceptionLayout.createSequentialGroup()
                .addComponent(jPanelConceptionTool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLayeredPane.add(jPanelConception, "card2");

        jPanelSimulationDraw.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSimulationDraw.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelSimulationDrawMouseMoved(evt);
            }
        });
        jPanelSimulationDraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSimulationDrawMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Simulation");

        javax.swing.GroupLayout jPanelSimulationTitleLayout = new javax.swing.GroupLayout(jPanelSimulationTitle);
        jPanelSimulationTitle.setLayout(jPanelSimulationTitleLayout);
        jPanelSimulationTitleLayout.setHorizontalGroup(
            jPanelSimulationTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSimulationTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSimulationTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSimulationTitleLayout.createSequentialGroup()
                        .addGap(0, 98, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(0, 98, Short.MAX_VALUE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelSimulationTitleLayout.setVerticalGroup(
            jPanelSimulationTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSimulationTitleLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelSimulationContainer.setLayout(new java.awt.GridLayout(0, 1));

        jPanelDeseaseParams.setBackground(new java.awt.Color(230, 230, 230));
        jPanelDeseaseParams.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        jLabel9.setText("Parametre de la maladie");
        jPanelDeseaseParams.add(jLabel9);

        jPanelMortalityRate.setLayout(new java.awt.GridLayout(1, 0));

        jLabelTitleMortalityRate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTitleMortalityRate.setText("Taux mortalite");
        jPanelMortalityRate.add(jLabelTitleMortalityRate);

        jTextFieldMortalityRate.setText("0%");
        jTextFieldMortalityRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMortalityRateActionPerformed(evt);
            }
        });
        jPanelMortalityRate.add(jTextFieldMortalityRate);

        jPanelDeseaseParams.add(jPanelMortalityRate);

        jPanelReproductionRate.setLayout(new java.awt.GridLayout(1, 0));

        jLabelTitleReproductionRate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTitleReproductionRate.setText("Taux reproduction");
        jPanelReproductionRate.add(jLabelTitleReproductionRate);

        jTextFieldReproductionRate.setText("0%");
        jPanelReproductionRate.add(jTextFieldReproductionRate);

        jPanelDeseaseParams.add(jPanelReproductionRate);

        jPanelCuredRate.setLayout(new java.awt.GridLayout(1, 0));

        jLabelTitleCuredRate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTitleCuredRate.setText("Taux guerison");
        jPanelCuredRate.add(jLabelTitleCuredRate);

        jTextFieldCuredRate.setText("0%");
        jPanelCuredRate.add(jTextFieldCuredRate);

        jPanelDeseaseParams.add(jPanelCuredRate);

        jPanelTransmissionRate.setLayout(new java.awt.GridLayout(1, 0));

        jLabelTitleTransmissionRate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTitleTransmissionRate.setText("Taux transmission");
        jPanelTransmissionRate.add(jLabelTitleTransmissionRate);

        jTextFieldTransmissionRate.setText("0%");
        jPanelTransmissionRate.add(jTextFieldTransmissionRate);

        jPanelDeseaseParams.add(jPanelTransmissionRate);

        jButtonApplyDisease.setText("Appliquer (maladie)");
        jButtonApplyDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplyDiseaseActionPerformed(evt);
            }
        });
        jPanelDeseaseParams.add(jButtonApplyDisease);

        jPanelSimulationContainer.add(jPanelDeseaseParams);

        jPanelMesureParams.setBackground(new java.awt.Color(230, 230, 230));
        jPanelMesureParams.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        jLabel11.setText("Parametre des mesures");
        jPanelMesureParams.add(jLabel11);

        jPanelAdhesionRate1.setLayout(new java.awt.GridLayout(1, 0));

        jLabelTitleMesureName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTitleMesureName.setText("Nom de la mesure");
        jPanelAdhesionRate1.add(jLabelTitleMesureName);

        jTextFieldMesureName.setText("Mesure X");
        jPanelAdhesionRate1.add(jTextFieldMesureName);

        jPanelMesureParams.add(jPanelAdhesionRate1);

        jPanelAdhesionRate.setLayout(new java.awt.GridLayout(1, 0));

        jLabelTitleAdhesionRate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTitleAdhesionRate.setText("Taux d'adhésion");
        jPanelAdhesionRate.add(jLabelTitleAdhesionRate);

        jTextFieldAdhesionRate.setText("0%");
        jPanelAdhesionRate.add(jTextFieldAdhesionRate);

        jPanelMesureParams.add(jPanelAdhesionRate);

        jPanelReproductionRate1.setLayout(new java.awt.GridLayout(1, 0));

        jLabelActive.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelActive.setText("Actif");
        jPanelReproductionRate1.add(jLabelActive);
        jPanelReproductionRate1.add(jCheckBoxActive);

        jPanelMesureParams.add(jPanelReproductionRate1);

        jButtonApplyMesure.setText("Créer une mesure");
        jButtonApplyMesure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplyMesureActionPerformed(evt);
            }
        });
        jPanelMesureParams.add(jButtonApplyMesure);

        jPanelSimulationContainer.add(jPanelMesureParams);

        jButtonSwitchConception.setText("Passer en conception");
        jButtonSwitchConception.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSwitchConceptionActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanelSimulationToolLayout = new javax.swing.GroupLayout(jPanelSimulationTool);
        jPanelSimulationTool.setLayout(jPanelSimulationToolLayout);
        jPanelSimulationToolLayout.setHorizontalGroup(
            jPanelSimulationToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSimulationToolLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelSimulationToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSimulationToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jPanelSimulationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelSimulationContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSwitchConception, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanelSimulationToolLayout.setVerticalGroup(
            jPanelSimulationToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSimulationToolLayout.createSequentialGroup()
                .addComponent(jPanelSimulationTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(jPanelSimulationContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 313, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(jButtonSwitchConception)
                .addGap(25, 25, 25))
        );

        jPanelOverview.setLayout(new java.awt.GridLayout(1, 0));

        jPanelCase.setPreferredSize(new java.awt.Dimension(700, 30));

        jLabelTitleCase.setText("Inféctés:");

        jLabelCase.setText("1000");

        javax.swing.GroupLayout jPanelCaseLayout = new javax.swing.GroupLayout(jPanelCase);
        jPanelCase.setLayout(jPanelCaseLayout);
        jPanelCaseLayout.setHorizontalGroup(
            jPanelCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaseLayout.createSequentialGroup()
                .addComponent(jLabelTitleCase, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCase, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelCaseLayout.setVerticalGroup(
            jPanelCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelTitleCase, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelCase, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelOverview.add(jPanelCase);

        jPanelDead.setPreferredSize(new java.awt.Dimension(700, 30));

        jLabelTitleDead.setText("Mort:");

        jLabelDead.setText("1000");

        javax.swing.GroupLayout jPanelDeadLayout = new javax.swing.GroupLayout(jPanelDead);
        jPanelDead.setLayout(jPanelDeadLayout);
        jPanelDeadLayout.setHorizontalGroup(
            jPanelDeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeadLayout.createSequentialGroup()
                .addComponent(jLabelTitleDead)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDead, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelDeadLayout.setVerticalGroup(
            jPanelDeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelTitleDead, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelDead, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelOverview.add(jPanelDead);

        jPanelDayElapsed.setPreferredSize(new java.awt.Dimension(700, 30));

        jLabelTitleDayElapsed.setText("Jour:");

        jLabelDayElapsed.setText("1000");

        javax.swing.GroupLayout jPanelDayElapsedLayout = new javax.swing.GroupLayout(jPanelDayElapsed);
        jPanelDayElapsed.setLayout(jPanelDayElapsedLayout);
        jPanelDayElapsedLayout.setHorizontalGroup(
            jPanelDayElapsedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDayElapsedLayout.createSequentialGroup()
                .addComponent(jLabelTitleDayElapsed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDayElapsed, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelDayElapsedLayout.setVerticalGroup(
            jPanelDayElapsedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDayElapsedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelTitleDayElapsed, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelDayElapsed, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelOverview.add(jPanelDayElapsed);

        javax.swing.GroupLayout jPanelSimulationLayout = new javax.swing.GroupLayout(jPanelSimulation);
        jPanelSimulation.setLayout(jPanelSimulationLayout);
        jPanelSimulationLayout.setHorizontalGroup(
            jPanelSimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSimulationLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jPanelOverview, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelSimulationLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanelSimulationDraw, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(jPanelSimulationTool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanelSimulationLayout.setVerticalGroup(
            jPanelSimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSimulationLayout.createSequentialGroup()
                .addComponent(jPanelOverview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSimulationLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanelSimulationDraw, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE))
                    .addGroup(jPanelSimulationLayout.createSequentialGroup()
                        .addComponent(jPanelSimulationTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(180, 180, 180))))
        );

        jLayeredPane.add(jPanelSimulation, "card3");

        jPanelContainer.add(jLayeredPane);

        jMenu3.setText("File");

        NouveauMenu.setLabel("Nouveau projet");
        NouveauMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NouveauMenuActionPerformed(evt);
            }
        });
        jMenu3.add(NouveauMenu);

        ChargerMenu.setLabel("Ouvrir un projet ");
        ChargerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChargerMenuActionPerformed(evt);
            }
        });
        jMenu3.add(ChargerMenu);

        SauvegarderMenu.setLabel("Sauvegarder le projet");
        SauvegarderMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SauvegarderMenuActionPerformed(evt);
            }
        });
        jMenu3.add(SauvegarderMenu);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 560, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSwitchConceptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSwitchConceptionActionPerformed
        countrySelected = null;
        countryPts.clear();
        
        jLayeredPane.removeAll();
        jLayeredPane.add(jPanelConception);
        jLayeredPane.repaint();
        jLayeredPane.revalidate();
        
        jPanelSimulationDraw.remove(drawingPanel);
        jPanelConceptionDraw.remove(drawingPanel);
        drawingPanel = new DrawingPanel(this, jPanelConceptionDraw);
        jPanelConceptionDraw.add(drawingPanel);
    }//GEN-LAST:event_jButtonSwitchConceptionActionPerformed

    private void jPanelSimulationDrawMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSimulationDrawMousePressed
        if(mode == Mode.Idle) {
            SelectCountry(evt.getPoint());
        }
//        } else if(mode != Mode.Create) {
//            SetSelectedCountry(null);
//        }
        LogiqueQuiNeDoitPasEtreIciNormalement(evt);
    }//GEN-LAST:event_jPanelSimulationDrawMousePressed

    private void jPanelSimulationDrawMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSimulationDrawMouseMoved
        LogiqueDeOnHoverQuiNeDoitPasEtreLa(evt);
    }//GEN-LAST:event_jPanelSimulationDrawMouseMoved

    private void jBtnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPlayActionPerformed
       worldController.StartSimulation();
    }//GEN-LAST:event_jBtnPlayActionPerformed

    private void jBtnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPauseActionPerformed
        worldController.pauseSimulation();
    }//GEN-LAST:event_jBtnPauseActionPerformed

    private void jBtnRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRedoActionPerformed
        worldController.Redo();
    }//GEN-LAST:event_jBtnRedoActionPerformed

    private void jBtnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUndoActionPerformed
   worldController.Undo();
    }//GEN-LAST:event_jBtnUndoActionPerformed

    private void jButtonApplyDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplyDiseaseActionPerformed
        System.out.println("on update disease");
        worldController.UpdateDisease(Double.parseDouble(jTextFieldCuredRate.getText()), Double.parseDouble(jTextFieldMortalityRate.getText()), Double.parseDouble(jTextFieldReproductionRate.getText()));
    }//GEN-LAST:event_jButtonApplyDiseaseActionPerformed

    private void jButtonApplyMesureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplyMesureActionPerformed
        System.out.println("on applique une mesure");
        worldController.AddMesure(Double.parseDouble(jTextFieldAdhesionRate.getText()), jCheckBoxActive.isSelected(), jTextFieldMesureName.getText());
        DefaultListModel listModel = new DefaultListModel();
        for (HealthMesureDTO m : worldController.GetHealthMesures()){
            listModel.addElement(m.MesureName);
        }
        jList1.setModel(listModel);
    }//GEN-LAST:event_jButtonApplyMesureActionPerformed

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        worldController.resetSimulation();
    }//GEN-LAST:event_jBtnResetActionPerformed

    private void SauvegarderMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SauvegarderMenuActionPerformed
        int returnValue = saveFileChooser.showSaveDialog(this);
        
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            worldController.save(saveFileChooser.getSelectedFile());
        }
        
    }//GEN-LAST:event_SauvegarderMenuActionPerformed

    private void ChargerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChargerMenuActionPerformed
        int returnValue = openFileChooser.showOpenDialog(this);
        
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            worldController.load(openFileChooser.getSelectedFile());
        }
        
    }//GEN-LAST:event_ChargerMenuActionPerformed

    private void NouveauMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NouveauMenuActionPerformed
        // TODO add your handling code here: MEL À CONFIGUER
    }//GEN-LAST:event_NouveauMenuActionPerformed


    private void jTextFieldMortalityRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMortalityRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMortalityRateActionPerformed

    private void jButtonSwitchSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSwitchSimulationActionPerformed
        countrySelected = null;
        countryPts.clear();

        jLayeredPane.removeAll();
        jLayeredPane.add(jPanelSimulation);
        jLayeredPane.repaint();
        jLayeredPane.revalidate();

        jPanelConceptionDraw.remove(drawingPanel);
        jPanelSimulationDraw.remove(drawingPanel);
        drawingPanel = new DrawingPanel(this, jPanelSimulationDraw);
        jPanelSimulationDraw.add(drawingPanel);
    }//GEN-LAST:event_jButtonSwitchSimulationActionPerformed

    private void jButtonAddLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddLinkActionPerformed
        mode = Mode.Select;
        SetSelectedCountry(null);
    }//GEN-LAST:event_jButtonAddLinkActionPerformed

    private void jTextCountryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCountryNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCountryNameActionPerformed

    private void jButtonRemoveCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveCountryActionPerformed
        if(countrySelected != null) {
            worldController.RemoveCountry(countrySelected.Id);
        }
    }//GEN-LAST:event_jButtonRemoveCountryActionPerformed

    private void jToggleButtonCreateCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCreateCountryActionPerformed
        // TODO add your handling code here:
        if (jToggleButtonCreateCountry.isSelected()){
            mode = Mode.Create;
            SetSelectedCountry(null);
            jPanelCountryInfo.setVisible(true);
        } else {
            mode = Mode.Idle;
            jPanelCountryInfo.setVisible(false);
        }
    }//GEN-LAST:event_jToggleButtonCreateCountryActionPerformed

    private void jPanelConceptionDrawMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelConceptionDrawMousePressed
        if(mode == Mode.Idle) {
            SelectCountry(evt.getPoint());
        }
        LogiqueQuiNeDoitPasEtreIciNormalement(evt);
    }//GEN-LAST:event_jPanelConceptionDrawMousePressed

    private void jPanelConceptionDrawMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelConceptionDrawMouseMoved
        LogiqueDeOnHoverQuiNeDoitPasEtreLa(evt);
    }//GEN-LAST:event_jPanelConceptionDrawMouseMoved

    private void jPanelConceptionDrawMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelConceptionDrawMouseDragged
        List<CountryDTO> countries = worldController.GetCountries();
        CountryDTO selected = Utility.SelectCountry(countries, evt.getPoint());
        if(selected != null) {
            selected.Shape.SetPosition(evt.getPoint());
            worldController.UpdateCountry(selected);
            drawingPanel.revalidate();
            drawingPanel.repaint();
        }
    }//GEN-LAST:event_jPanelConceptionDrawMouseDragged

    private void jButtonRemoveLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveLinkActionPerformed
        List<LinkDTO> links = worldController.GetLinks();
        int[] index = jlistLinks.getSelectedIndices();
        
        for(int i = 0; i < index.length; i++) {
            UUID id = links.get(index[i]).Id;
            worldController.RemoveLink(id);
        }
    }//GEN-LAST:event_jButtonRemoveLinkActionPerformed

    private void jlistLinksValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlistLinksValueChanged
        List<LinkDTO> links = worldController.GetLinks();
        for(LinkDTO l: links) {
            if(l.IsSelected) {
                worldController.UpdateSelectionStateLink(l.Id, false);
            }
        }
        
        int[] index = jlistLinks.getSelectedIndices();
        for(int i = 0; i < index.length; i++) {
            UUID id = links.get(index[i]).Id;
            worldController.UpdateSelectionStateLink(id, true);
        }
        drawingPanel.repaint();
    }//GEN-LAST:event_jlistLinksValueChanged
 
    
    public void Draw(Graphics g){
        worldController.Draw(g);
        if(onHoverCountry != null) {
            worldController.DrawCountryInfo(g, onHoverMousePosition, onHoverCountry);
        }
    }
    
    public void LogiqueDeOnHoverQuiNeDoitPasEtreLa(java.awt.event.MouseEvent evt) {
        if(mode == Mode.Idle) {
            Point mousePoint = evt.getPoint();
            List<CountryDTO> countries = worldController.GetCountries();
            CountryDTO selected = Utility.SelectCountry(countries, mousePoint);
            boolean found = false;
            
            if(selected != null) {
                onHoverCountry = selected;
                onHoverMousePosition = mousePoint;
                found = true;
            }
            
            if(!found) {
                onHoverCountry = null;
            }
            
            drawingPanel.repaint();
        } else {
            onHoverCountry = null;
        }
    }
    
    public void LogiqueQuiNeDoitPasEtreIciNormalement(java.awt.event.MouseEvent evt) {        
        if(mode == Mode.Select && evt.getButton() == MouseEvent.BUTTON1) {
            Point mousePoint = evt.getPoint();
            
            List<CountryDTO> countries = worldController.GetCountries();
            CountryDTO selected = Utility.SelectCountry(countries, mousePoint);
            boolean found = false;
            if(selected != null) {
                if(countrySelected != null) {
                    int linkIndex = jComboBoxLinkType.getSelectedIndex();
                    worldController.AddLink(countrySelected.Id, selected.Id, LinkType.values()[linkIndex]);
                    mode = Mode.Idle;
                    SetSelectedCountry(null);
                } else {
                    countrySelected = selected;
                    found = true;
                }
            }
 
            if(!found) {
                countrySelected = null;
            }
        } else if(mode == Mode.Create && evt.getButton() == MouseEvent.BUTTON1) {
            countryPts.add(evt.getPoint());
            
            if(countryPts.size() == 2) { // Un peux bete de faire ca, mais on trouvera une solution
                worldController.AddCountry(countryPts, jTextCountryName.getText(), Integer.parseInt(jTextCountryPop.getText()));
                drawingPanel.repaint();

                countryPts.clear();
                //mode = Mode.Idle;
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_window_Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_window_Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_window_Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_window_Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_window_Simulation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ChargerMenu;
    private javax.swing.JLabel LabelCountryName;
    private javax.swing.JMenuItem NouveauMenu;
    private javax.swing.JMenuItem SauvegarderMenu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jBtnPause;
    private javax.swing.JButton jBtnPlay;
    private javax.swing.JButton jBtnRedo;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnUndo;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButtonAddLink;
    private javax.swing.JButton jButtonAddRegion;
    private javax.swing.JButton jButtonApplyDisease;
    private javax.swing.JButton jButtonApplyMesure;
    private javax.swing.JButton jButtonEditCountry;
    private javax.swing.JButton jButtonEditRegion;
    private javax.swing.JButton jButtonRemoveCountry;
    private javax.swing.JButton jButtonRemoveLink;
    private javax.swing.JButton jButtonRemoveRegion;
    private javax.swing.JButton jButtonSwitchConception;
    private javax.swing.JButton jButtonSwitchSimulation;
    private javax.swing.JCheckBox jCheckBoxActive;
    private javax.swing.JComboBox<String> jComboBoxLinkType;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelActive;
    private javax.swing.JLabel jLabelCase;
    private javax.swing.JLabel jLabelCountryPop;
    private javax.swing.JLabel jLabelDayElapsed;
    private javax.swing.JLabel jLabelDead;
    private javax.swing.JLabel jLabelTitleAdhesionRate;
    private javax.swing.JLabel jLabelTitleCase;
    private javax.swing.JLabel jLabelTitleCuredRate;
    private javax.swing.JLabel jLabelTitleDayElapsed;
    private javax.swing.JLabel jLabelTitleDead;
    private javax.swing.JLabel jLabelTitleMesureName;
    private javax.swing.JLabel jLabelTitleMortalityRate;
    private javax.swing.JLabel jLabelTitleReproductionRate;
    private javax.swing.JLabel jLabelTitleTransmissionRate;
    private javax.swing.JLayeredPane jLayeredPane;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAdhesionRate;
    private javax.swing.JPanel jPanelAdhesionRate1;
    private javax.swing.JPanel jPanelCase;
    private javax.swing.JPanel jPanelConception;
    private javax.swing.JPanel jPanelConceptionContainer;
    private javax.swing.JPanel jPanelConceptionDraw;
    private javax.swing.JPanel jPanelConceptionTitle;
    private javax.swing.JPanel jPanelConceptionTool;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelCountry;
    private javax.swing.JPanel jPanelCountryInfo;
    private javax.swing.JPanel jPanelCuredRate;
    private javax.swing.JPanel jPanelDayElapsed;
    private javax.swing.JPanel jPanelDead;
    private javax.swing.JPanel jPanelDeseaseParams;
    private javax.swing.JPanel jPanelLink;
    private javax.swing.JPanel jPanelMainButtons;
    private javax.swing.JPanel jPanelMesureParams;
    private javax.swing.JPanel jPanelMortalityRate;
    private javax.swing.JPanel jPanelOverview;
    private javax.swing.JPanel jPanelRegion;
    private javax.swing.JPanel jPanelReproductionRate;
    private javax.swing.JPanel jPanelReproductionRate1;
    private javax.swing.JPanel jPanelSimulation;
    private javax.swing.JPanel jPanelSimulationContainer;
    private javax.swing.JPanel jPanelSimulationDraw;
    private javax.swing.JPanel jPanelSimulationTitle;
    private javax.swing.JPanel jPanelSimulationTool;
    private javax.swing.JPanel jPanelTransmissionRate;
    private javax.swing.JPanel jPanelUndoRedoButtons;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextCountryName;
    private javax.swing.JTextField jTextCountryPop;
    private javax.swing.JTextField jTextFieldAdhesionRate;
    private javax.swing.JTextField jTextFieldCuredRate;
    private javax.swing.JTextField jTextFieldMesureName;
    private javax.swing.JTextField jTextFieldMortalityRate;
    private javax.swing.JTextField jTextFieldReproductionRate;
    private javax.swing.JTextField jTextFieldTransmissionRate;
    private javax.swing.JToggleButton jToggleButtonCreateCountry;
    private javax.swing.JList<String> jlistLinks;
    // End of variables declaration//GEN-END:variables
}
